import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { WingPluginContext } from "../wing-plugin.js";
import { registerAutoCompressTools } from "./auto-compress.js";
import { registerAutoGainTools } from "./autogain.js";
import { registerAutoGateTools } from "./auto-gate.js";
import { registerBusMainMatrixTools } from "./bus-main-matrix.js";
import { registerChannelTools } from "./channel.js";
import { registerDcaMutegroupTools } from "./dca-mutegroup.js";
import { registerDelayTools } from "./delay.js";
import { registerDynamicsStatusTools } from "./dynamics-status.js";
import { registerFadeTools } from "./fade.js";
import { registerGenericTools } from "./generic.js";
import { registerGroupTools } from "./groups.js";
import { registerInputPatchTools } from "./input-patch.js";
import { registerInsertTools } from "./insert.js";
import { registerLinkStatusTools } from "./link-status.js";
import { registerMatrixDirectTools } from "./matrix-direct.js";
import { registerMeterStatsTools } from "./meter-stats.js";
import { registerNameListTools } from "./names.js";
import { registerPresetTools } from "./presets.js";
import { registerProcessingToggleTools } from "./processing-toggle.js";
import { registerProcOrderTools } from "./proc-order.js";
import { registerRoutingTools } from "./routing.js";
import { registerRtaTools } from "./rta.js";
import { registerSaveFlashTools } from "./save-flash.js";
import { registerSceneTools } from "./scenes.js";
import { registerSelectedStripTools } from "./selected-strip.js";
import { registerUsbPlayerTools } from "./usb-player.js";
import { registerValueMemoryTools } from "./value-memory.js";
import { registerWingLiveTools } from "./wing-live.js";

/** Registers the whole WING MCP tool surface (generic escape hatch + convenience families) on `server`. */
export function registerWingTools(server: McpServer, ctx: WingPluginContext): void {
  registerGenericTools(server, ctx);
  registerChannelTools(server, ctx);
  registerBusMainMatrixTools(server, ctx);
  registerDcaMutegroupTools(server, ctx);
  registerDelayTools(server, ctx);
  registerGroupTools(server, ctx);
  registerRoutingTools(server, ctx);
  registerSceneTools(server, ctx);
  registerNameListTools(server, ctx);
  registerPresetTools(server, ctx);
  registerFadeTools(server, ctx);
  registerRtaTools(server, ctx);
  registerMeterStatsTools(server, ctx);
  registerAutoGainTools(server, ctx);
  registerDynamicsStatusTools(server, ctx);
  registerAutoCompressTools(server, ctx);
  registerAutoGateTools(server, ctx);
  registerUsbPlayerTools(server, ctx);
  registerInsertTools(server, ctx);
  registerProcessingToggleTools(server, ctx);
  registerProcOrderTools(server, ctx);
  registerInputPatchTools(server, ctx);
  registerLinkStatusTools(server, ctx);
  registerMatrixDirectTools(server, ctx);
  registerSaveFlashTools(server, ctx);
  registerSelectedStripTools(server, ctx);
  registerValueMemoryTools(server, ctx);
  registerWingLiveTools(server, ctx);
}
